### ISSUE TITLE
Support for/Show twelve-seed phrase option 

### ISSUE THREAD

**Issue by tirumerla** [blockstack/stacks-wallet#112]
**Is your feature request related to a problem? Please describe.**

- As of now, there is no way to gain access/ "restore from seed phrase" to the wallet to make transactions ( send or receive ) or to view balances ( other than explorer ) using twelve-seed phrase. The only option available is by using twenty four seed phrase.

**Describe the solution you'd like**

- Ability to restore wallet from seed phrase by supporting twelve-seed phrase
- Displaying it for the users using a small modal on the UI.

**Describe alternatives you've considered**

- Run Wallet locally and change the code from wallet to use 12 seed phrase instead of 24 seed phrase.

**Additional context**

- I was not able to login with my 12 seed phrase with latest versions of the wallet since newer versions are supporting 24 seed phrase. 

- I had to manually clone the repo make changes locally to update the codebase to support 12 seed phrase where i was able to gain access to my wallet. 

- Others might face the same issues if they haven't created new wallet with 24 seed phrase and have added 12 seed phrase wallet address as part of the token sale.

**Comment by kantai** [comment]
This seems to have come up a number of times -- users had 12-word seed phrases because prior wallet versions allowed those to be used (though I don't think the stacks wallet software ever _generated_ 12-word seed phrases).

**Comment by markmhx** [comment]
@tirumerla Mind if I ask how you originally generated this 12-word phrase you'd like to use with the Stacks Wallet?

**Comment by yknl** [comment]
The current version of the wallet does not allow you to restore from a 12 word seed phrase because since the first version, it has always generated 24 word seed phrases. The confusion I believe is from users who wrote down their **Blockstack Browser seed phrase** (which was 12 words) and labeled it as "Blockstack". And later on try to use it to restore their Stacks wallet.

**Comment by tirumerla** [comment]
> @tirumerla Mind if I ask how you originally generated this 12-word phrase you'd like to use with the Stacks Wallet?
> 

I agree with @yknl i think it's definitely via **Blockstack Browser Seed phrase**.

**Comment by wolfenhawke** [comment]
For original supporters of Blockstack and Stacks, a desktop app was provided in order to receive the coins from the investment. This app (not a Blockstack browser app) provided 12 word seed phrases (maybe there was a choice for 24, but I don't remember). So, anyone who invested and forgot (hodl'd so to speak), is in this conundrum. This stacks app was a black square with 4 white dots, not the blue square now. That wallet was named "Blockstack".

**Comment by yknl** [comment]
@wolfenhawke the Stacks wallet v1.0 was the app provided to early supporters that you're referring to. However, the Stacks wallet has always provided 24 word seed phrases, there was never any other choice. There's no way you could have gotten a 12 word phrase from participating in the sale. Again, this is most likely a wrongly labeled seed phrase from the Blockstack browser.

**Comment by lamoquette** [comment]
I have the similar problem. I have the 12 words seed phrase but I'm not able to recovery my Blockstack wallet.

We can see in these documentation : https://docs.blockstack.org/references/glossary or https://docs.blockstack.org/stacks-wallet/security

> Secret Recovery Key
> Used to access an identity on the Blockstack blockchain. A 24-word sequence of words for example:
> 
> **The early Blockstack recovery keys were 12-word sequences**.

**Comment by yknl** [comment]
@lamoquette the documentation is incorrect and will be fixed shortly. See the previous explanation for why 12-word seed phrases were not from the Stacks wallet.

**Comment by markmhx** [comment]
I'm closing this out in favor of our plans on https://github.com/blockstack/stacks-wallet/issues/253 to support 12-word phrases in the new wallet.

**Comment by tirumerla** [comment]
> I'm closing this out in favor of our plans on #253 to support 12-word phrases in the new wallet.

Thanks @markmhx. Appreciate for adding this feature in the new version of the wallet.

**Comment by jwall** [comment]
> For original supporters of Blockstack and Stacks, a desktop app was provided in order to receive the coins from the investment. This app (not a Blockstack browser app) provided 12 word seed phrases (maybe there was a choice for 24, but I don't remember). So, anyone who invested and forgot (hodl'd so to speak), is in this conundrum. This stacks app was a black square with 4 white dots, not the blue square now. That wallet was named "Blockstack".

I was using the previous desktop stacks wallet. It showed my unlocked STX balance correctly. I just now installed the new wallet app over top the previous wallet app. I used my 12 word seed phrase, and now my balance shows zero. Where do I go or what do I do to resolve this issue (in hindsight I should have kept both apps)? I see now 24 word seed phrases are used.

**Comment by kyranjamie** [comment]
@jwall Where did you get the 12-word phrase from? It's more than likely this was from the Blockstack browser, rather than the Stacks Wallet. Are you sure that you didn't save a 24-word phrase somewhere, which _is_ the key to your funds?

[Check out this section of the Wallet's FAQ for more info](https://www.hiro.so/questions/what-are-secret-keys-and-how-do-they-work)

**Comment by jwall** [comment]
I found a screen shot of my 24 word seed phase - whew! Thank you for your quick response. Time for some Spring cleaning on my part :slight_smile:
