### ISSUE TITLE
Stacks Wallet hangs on "Loading" with Ledger Nano S

### ISSUE THREAD

**Issue by laytond** [blockstack/stacks-wallet#124]
**Description**

After initiating a send transaction from Stacks Wallet using a Ledger Nano S, the Ledger Nano S never prompts to approve transactions while the Stacks Wallet screen hangs up on the the "Loading" step.

**Steps To Reproduce**
1. Open Stacks Wallet
2. Click on Send
3. Prepare send transaction
4. Click on Continue
5. Proceed through the "Connect your Ledger" steps
6. On the Ledger Nano S, unlock and open the Bitcoin app (shows "Application is ready")
7. Observe that the last screen of the "Connect your Ledger" steps says "Loading" on the button
8. Observe that the Ledger Nano S never prompts for transaction approval (continues to show "Application is ready")
Note: These exact steps functioned properly less than 24 hours ago.

**Expected behavior**

On step 8 above, I should be prompted to approve the transaction on the Ledger Nano S.

**Screenshots**
![image](https://user-images.githubusercontent.com/10748468/74092128-d5b08a80-4a74-11ea-93ae-68475b7e5359.png)

**Desktop**
 - macOS 10.14.6 (18G103)
 - Stacks Wallet Version 3.0.0 (3.0.0)

**Comment by yknl** [comment]
Thanks for reporting. Did you perform any firmware updates on the Ledger between when it was working and when it stopped?

**Comment by laytond** [comment]
Hi @yknl -- I did not upgrade my firmware between the uses.

**Comment by yknl** [comment]
Can you confirm that you have enough BTC in your fuel address for the transaction? Some times a little bit more than the estimated amount is required.

**Comment by laytond** [comment]
I do have enough currently, yes. 

Though it may be worth mentioning that the last transaction I successfully processed reduced the balance below the minimum BTC threshold. At that point I began seeing the prompt to add more BTC — which I did (so I don't see that prompt anymore). Since this point I've been running into the issue outlined.

And one more note: I reset my wallet just to see if that would help. No luck there.

**Comment by whiteyhat** [comment]
<img width="601" alt="Captura de pantalla 2020-02-20 a las 10 59 31" src="https://user-images.githubusercontent.com/31220861/74922847-2064c780-53d0-11ea-98ef-2c8b27fe50fb.png">


I have enough BTC.. always same error....

**Comment by SHagege** [comment]
I have the same issue (and had it for weeks actually, I've never been able to proceed a single transaction because the wallet doesn't see my Ledger). 

Yesterday it prompted me that my BTC balance wasn't enough to proceed the transaction (by the way 0.0004BTC for a tx when I could do a 1 sat/vB tx at the same time? How is it calculated?), but now that I guess the network is less congestioned and that my balance is enough again I just have this "Connect your Ledger" screen and can't do anything with it.

**Comment by whiteyhat** [comment]
The worst thing of all is that I do not have the wallet seed and I need to restore the laptop. I wish this wallet could work without issues otherwise I will bee losing so much...

**Comment by whiteyhat** [comment]
@yknl can we find a fix for this?

**Comment by yknl** [comment]
@whiteyhat some times the estimates for the fuel costs are off. The actual transaction costs depends on the number of unspent outputs in the fuel address. Can you try sending a larger amount of BTC to the fuel address and try again? I would try with more than enough BTC for a few transactions.

**Comment by laytond** [comment]
Hi @yknl I believe the issue we're all having is that regardless of the amount of BTC available for fuel, Blockstack Wallet is not generating transactions that Ledger Nano S recognizes. 

Are you suggesting that if we added a certain amount of BTC (in addition to the threshold required to _not_ see the insufficient BTC error), the software would work? If so, what amount of BTC is that?

**Comment by whiteyhat** [comment]
I have ~5USD in in BTC. Let me add 15USD. 

Also, this is dramatic and it should be more specified/notified to the user...

**Comment by whiteyhat** [comment]
I added 25USD and still not working...

**Comment by yknl** [comment]
@whiteyhat can you provide your Stacks address and fuel address privately for us to diagnose your issue? Send an email over to support at Blocktack.

**Comment by whiteyhat** [comment]
> @whiteyhat can you provide your Stacks address and fuel address privately for us to diagnose your issue? Send an email over to support at Blocktack.

Just contacted you on slack privately

**Comment by laytond** [comment]
@yknl I just sent an email to Support with my addresses as well. Still locked out of sending from the wallet — I've got 0.00179754 BTC (~$15) in BTC in the fuel address currently.

**Comment by laytond** [comment]
Just posting an update on here for others with the same issue.

Support (via Ken) suggested adding additional BTC to my fuel address. After bringing the balance on my account up to 0.00329754 BTC, the same issue persists. I let them know about a week ago that it didn't work, so just waiting for a follow-up.

They also recommended confirming that I double check that I was using the correct Ledger (just in case I had multiple).

Will share whatever I hear.

**Comment by SHagege** [comment]
Thanks. I have this issue since November I think, I've never been able to send any STX with my Ledger. And since it's most probably an issue with the wallet itself and we're at version 3.0 since months, I'm honestly surprised we are the first ones to complain.

**Comment by gigamesh** [comment]
I have the same issue

**Comment by markmhx** [comment]
My apologies to everyone who's encountered this problem and has been waiting for a solution 🙏 

Blockstack PBC recently began work on a new Stacks Wallet for [Stacks 2.0](https://blog.blockstack.org/stacks-2-testnet/) since we need to upgrade how wallet functionality works across the board. And we've factored in fuller Ledger support into those plans, which should resolve this hanging issue.

Mainnet release for Stacks 2.0 is [tentatively slated for June or July](https://blockstack.org/roadmap) so this solution will not be available until then.

Do any of you have a pressing need for Ledger support here that can't wait another month or two?Please let me know if that's indeed the case since it'll help us assess whether a separate, more urgent hotfix is needed for the existing wallet.

Note that we'll also provide at the time of mainnet release a method for extracting any excess BTC you may have transferred into the Stacks Wallet, while trying to resolve this problem or otherwise.

**Comment by laytond** [comment]
Thank you for the update on this one @markmhx. Speaking only for myself, I am good with waiting — though it would be awesome to have clear visibility into the wallet's progress (including if there are any anticipated delays).

**Comment by markmhx** [comment]
Sounds good! We'll update this comment thread when we have a clearer idea of the launch date for this new wallet and corresponding Ledger support. And, of course, if we make any change to the current wallet that rectifies this issue, we'll provide an update about that as well!

**Comment by gigamesh** [comment]
Any update on this?

**Comment by gigamesh** [comment]
Btw, you raised $47.5 million in your ICO and your token is up almost 3x in the past few months. How is it with all those resources, it takes months to fix a bug in your wallet?

**Comment by markmhx** [comment]
Hi all, I'd like to provide an update on the new wallet work as previously mentioned [above](https://github.com/blockstack/stacks-wallet/issues/124#issuecomment-625741027). 

We've just released a "developer preview" version of the new wallet for testing as part of [the "Krypton" release of the Stacks 2.0 Testnet](https://blog.blockstack.org/krypton-launch-proof-of-transfer-now-implemented-on-the-stacks-2-0-testnet/). You can find related information and instructions for downloading the wallet [here](https://www.blockstack.org/p/stacks-wallet).

**Note**: This release works only on _testnet_ for the new Stacks 2.0 blockchain with _testnet STX_ (as available, for example, from [the testnet faucet](https://www.blockstack.org/testnet/faucet)). You won't be able to use it quite yet for managing _production_ STX with your Ledger device.

However, we've invested quite a lot in supporting Ledger comprehensively ahead of mainnet release. And we're keen on getting all of your bug reports and feedback leading up to that release to ensure that your Ledger device types work without a hitch by that point. Please help us out with testing if – and only if – you have a Ledger device available that does not hold your production STX.

I apologize to everyone here that getting a Ledger fix into production has taken significantly longer expected. Stacks 2.0 has been a large effort for all of us at Blockstack PBC, and it's been tricky determining just how to allocate resources towards its release vs. patching 1.0-based software, especially against a fluid timeline. We certainly appreciate your patience while we work towards this significant milestone for the Stacks ecosystem and do our best to juggle everything involved. 🙏 

On a related note, part of our team _is_ working to patch the existing wallet to permit BTC withdrawals ahead of mainnet, since the BTC component of the wallet will get dropped entirely upon Stacks 2.0 and we want to make it easy to get your BTC back. That work is getting tracked with https://github.com/blockstack/stacks-wallet/issues/131.

**Comment by laytond** [comment]
Thanks for the update on this @markmhx. 

One question about the BTC withdrawal feature on [version 3.1](https://github.com/blockstack/stacks-wallet/releases/tag/v3.1.0), given that it still relies on Ledger support to sign the transaction do you know if the 4.0 wallet (with Ledger support) will retain BTC support? If not, we'll still need a Ledger fix on the older wallet.

**Comment by markmhx** [comment]
We plan on removing BTC capabilities entirely in 4.0 so we do need to come up with a solution here for existing 3.x users that have trapped BTC _and_ trouble authenticating with Ledger Nano S devices.

Mind if I ask that you (or anyone else in this situation) email me to figure out the best option available given your particular needs? mark@blockstack.com

**Comment by laytond** [comment]
Sure thing, I'll email you @markmhx

**Comment by upandbeyond** [comment]
Is this STILL not fixed?? Ledger users can't send funds since at least February? You promised it back in June or July and it is now OCTOBER. I am trying to send funds and have this same issue, hung on LOADING.. Also with BTC mempool so backlogged it is incredible how much it costs in BTC to send STX.. I can't believe that STX transactions can't be paid in STX. How can I transfer funds from my Ledger???? Thank you.

**Comment by markmhx** [comment]
Hi @upandbeyond, I just followed up with your emails with a couple of questions and possible steps towards resolving your problems here. Thanks for sending me the additional information 🙏

**Comment by cherifzouein** [comment]
Any chance we could get an update on development? This issue impedes any movement of STX for users who use ledger as their wallet. If it has been as such since February it's  bit troubling. 

Thanks in advance!

**Comment by markmhx** [comment]
PBC is aiming to release Stacks 2.0 and the new Stacks Wallet by mid-December; however this remains tentative guidance. Please see [this blog post](https://blog.blockstack.org/when-stacks-2/) for more context on the overall workload and timing. And as always, thanks to everyone for your continued patience. 🙏

If anyone has an urgent need to move their STX from a Ledger Nano S device that's experiencing this problem in the meantime, please contact me at mark@blockstack.com to evaluate workaround options that may be suitable to your needs.

**Comment by vysegrad** [comment]
@markmhx @cherifzouein @upandbeyond @laytond @gigamesh @yknl 
I have found a workaround for this bug which is to install version 3.0 of the wallet. I have tested this on Mac OS X Big Sur and was able to access my wallet using the Ledger Nano S.

Version 3.0 download links:

https://github.com/blockstack/stacks-wallet/releases/download/v3.0.0/Stacks-Wallet-macOS-3.0.0.dmg

https://github.com/blockstack/stacks-wallet/releases/download/v3.0.0/Stacks-Wallet-win10-3.0.0.exe

@markmhx could you please provide information on the projected migration path into Stacks 2? How will Stacks holders be able to access their STX when using the Bitcoin wallet on Ledger Nano S and in particular those users who still have an unlocked future reserve of Stacks tokens?

**Comment by markmhx** [comment]
As for accessing STX upon release of Stacks 2.0, Stacks holders will not need to do anything apart from installing the new version of the Stacks Wallet (v4.0; still under development) and authenticating with their same hardware device or Secret Key in software mode.

As for BTC, Stacks 2.0 will not require nor support BTC for transaction fees. So users are encouraged, either before or after the release of Stacks 2.0, to use the latest wallet release (v3.1; found currently at https://wallet.blockstack.org/) to withdraw any BTC they'll no longer need to cover transaction fees with Stacks 1.0.

Any users with STX that have yet to unlock since purchase will continue to see those STX unlock and made available, the same in Stacks 2.0 as in Stacks 1.0. There are no steps necessary for users to make in regards to that unlocking process. All relevant unlocking data will get ported over automatically from Stacks 1.0 to 2.0.

**Comment by cherifzouein** [comment]
@vysegrad thank you that did the trick!

**Comment by cassiusgray** [comment]
@vysegrad's solution still working FYI

**Comment by Longvictory** [comment]
I use trezor wallet. There’s same problem, I can’t send my STX

**Comment by markmhx** [comment]
@Longvictory Are you trying with a Trezor Model T by chance per https://github.com/blockstack/stacks-wallet/issues/383?

**Comment by markmhx** [comment]
The new Stacks Wallet has arrived for Stacks 2.0! https://www.hiro.so/wallet/install-desktop

Please try it out with your Ledger Nano S and let us know if you have any problems. And thanks once again for your patience. 🙏

**Comment by SHagege** [comment]
Hi @markmhx 

I tried to use it this morning. But the Stack Ledger app is not out on their Ledger Live store yet. So we can't test anything, unfortunately.

**Comment by aulneau** [comment]
> Hi @markmhx
> 
> I tried to use it this morning. But the Stack Ledger app is not out on their Ledger Live store yet. So we can't test anything, unfortunately.

See instructions here for the ledger live app -> https://www.hiro.so/questions/how-can-i-use-my-ledger-device-with-stacks-wallet-v4-x :)

**Comment by cdmackie** [comment]
> > Hi @markmhx
> > I tried to use it this morning. But the Stack Ledger app is not out on their Ledger Live store yet. So we can't test anything, unfortunately.
> 
> See instructions here for the ledger live app -> https://www.hiro.so/questions/how-can-i-use-my-ledger-device-with-stacks-wallet-v4-x :)

Tried that, go through the steps and click Approve on the Ledger device, but it then just sits there.

![image](https://user-images.githubusercontent.com/314609/104662549-eeabbd80-567f-11eb-9c0b-c91ba91b8fac.png)

v3.0 workaround above from vysegrad didn't work either. Still can't transfer any STX out of my address, or get the BTC out that's stuck in there.

**Comment by aulneau** [comment]
@cdmackie there was a hot fix released, can you confirm that you are on 4.0.1?

**Comment by cdmackie** [comment]
> @cdmackie there was a hot fix released, can you confirm that you are on 4.0.1?

yes, 4.0.1.

**Comment by markmhx** [comment]
@cdmackie It appears you're seeing the same as reported and getting investigated here, correct? https://github.com/blockstack/stacks-wallet/issues/500

**Comment by cdmackie** [comment]
> @cdmackie It appears you're seeing the same as reported and getting investigated here, correct? #500

@markmhx ah yes, it does, thanks. It is a Nano X although I also tried my Nano S and got the same problem.

**Comment by markmhx** [comment]
@cdmackie mind indicating the firmware version of your Nano S that's giving you this difficulty?

**Comment by cdmackie** [comment]
@markmhx I was trying wallet v3 with the Nano S, but I just tried v4.01 on Nano S 1.6.1 and it gets stuck detected the Stacks app. Can't go any further. App opens on ledger itself.

**Comment by markmhx** [comment]
@cdmackie Mind trying with v4.0.2 by downloading from https://www.hiro.so/wallet/install-desktop? We pushed an upgrade that may have fixed this problem. Note as well that you'll need to have Ledger Live closed when attempting to sign into the wallet.

**Comment by julianlcarter** [comment]
I'm stuck too! Need to release my stacks and unable to do so.

**Comment by markmhx** [comment]
@cdmackie I sense you may have encountered the UX problem we're tracking here with your Nano S device: https://github.com/blockstack/stacks-wallet/issues/545

As for Nano X, we're looking to push a fix soon this week that resolves problems with sending STX: https://github.com/blockstack/stacks-wallet/issues/500

Much thanks for this info!

@julianlcarter Mind telling me what kind of Ledger device you're using (S or X), the version of the Stacks Wallet you're using, and just what you see when trying to send STX?

**Comment by julianlcarter** [comment]
I'm using Nano S.
Stacks wallet 4.0.2

My stacks transferred successfully to KuCoin once i upgraded Ledger to 1.6.1 firmware.

**Comment by julianlcarter** [comment]
Struggling to get some BTC gas from Stacks Wallet. 

I installed v 3.1.1 to get access to BTC. 

I try to send the BTC to Kucoin BTC address but it gets stuck on the last stage.

Stacks wallet says "Connect Your Ledger. Make Sure you have browser support set to 'no'. SIGNING. 

I open the BTC wallet on Ledger Nano S but Stacks wallet gets stuck on Signing. 

There is no longer any option to set browser support to no on Ledger Nano S.

**Comment by markmhx** [comment]
@julianlcarter Sending STX with the v3.1.1 wallet is no longer possible since it's connected to Stacks 1.0, which has entered read-only mode. You'll need to download the v4.x wallet and try sending there, where BTC is not needed for gas at all: https://www.hiro.so/wallet/install-desktop

**Comment by markmhx** [comment]
@julianlcarter Please contact me via these instructions so I can help you out over email: https://github.com/blockstack/stacks-wallet/issues/124#issuecomment-709329494

**Comment by zapnap** [comment]
@markmhx having the same issue. sent you an email a week or so back. would be great to get this resolved! thanks in advance

**Comment by markmhx** [comment]
@zapnap Mind sending me another email at mark@hiro.so or mark@blockstack.com? I don't see yours in my inbox for some reason.

**Comment by markmhx** [comment]
If you need to withdraw BTC from the older Stacks Wallet, please follow the following instructions for doing so with Electrum instead of trying to use v3.1.1, which is no longer supported and has known connectivity issues with hardware devices:

https://www.hiro.so/questions/how-can-i-withdraw-the-btc-ive-deposited-into-the-stacks-wallet
