### ISSUE TITLE
Change welcome screen subtitle

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/stacks-wallet#188]
From: 

![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/5599da84-62d1-490c-831e-247b2cb82db2)

To:

https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=220%3A4557

**Comment by markmhx** [comment]
This is integrated but let's remove the Oxford comma for simplicity:

<img width="413" alt="Screen Shot 2020-08-12 at 13 50 51" src="https://user-images.githubusercontent.com/28991/90012023-e4396200-dca2-11ea-9fb1-93c249555cbd.png">

**Comment by kyranjamie** [comment]
Repetition of STX seems rather redundant to me. No one reads this and think "Ohhh, that's what it does".

To be argumentative on the grammar front, one could argue without the Oxford comma there's the implication than earning Bitcoin is a result of sending and receiving STX.

How about "Participate in stacking to earn Bitcoin rewards".

**Comment by markmhx** [comment]
"Manage your STX holdings and earn Bitcoin rewards" would be simpler still...and no commas at all!

**Comment by kyranjamie** [comment]
@markmhx This has the same implication that earning Bitcoin rewards is a result of managing your STX holdings.

**Comment by markmhx** [comment]
I'm skeptical that most people would draw that implication from a simple "and" here. I imagine _some_ people would, but even then, it's unlikely to steer them far off course since they'll see dedicated UI for Stacking once inside anyway.

That said, how does "Manage your STX holdings and participate in Stacking" avoid the implication any more than "Manage your STX holdings and earn Bitcoin rewards"? Since you don't inherently participate in Stacking after managing your holdings anymore than you inherently earn Bitcoin rewards.

However we phrase this, I'd like to emphasize two things if possible:

- The wallet provides both STX management _and_ Stacking / BTC earning functionality. We'd be remiss to omit one of those features upon reminding the user "why they're here" post-install.
- While users who've already installed this wallet are more likely than the average Internet user to have heard of Stacking, we'd cast a wider net by referring to "earning BTC" instead of "Stacking" until the latter term catches hold. We tend to phrase "earn BTC rewards" inside the wallet for this reason.

<img width="411" alt="Screen Shot 2020-08-17 at 09 29 13" src="https://user-images.githubusercontent.com/28991/90369521-36e09880-e06c-11ea-8e34-b99f84da9faf.png">

With that said, I'll throw it back to you two to wordsmith. I promise not to lodge more complaints about commas 😄

p.s. in the screenshot above, are we overpromising with the phrase "...you'll earn Bitcoin every week"? We may want to say something like "...you'll have the chance to earn Bitcoin weekly".

**Comment by jasperjansz** [comment]
I like "Manage your STX holdings and earn Bitcoin rewards". 

My attempt with this card is not to have a perfect representation of the rules and rewards, the next screen features all the fine print and disclaimers.

**Comment by kyranjamie** [comment]
My rationale was that the verb "participate" requires an action, more so than "earn". But happy to accept this is also ambiguous. Let's not use that either.

I just find it difficult to see how it's responsible to use language that could, even remotely, give people the impression they get free money for something they don't. Ambiguity is dangerous. Why risk confusing even one person, when there's an infinite selection of other unambiguous sentences to choose from?

Can we not just qualify it: _Manage your STX holdings, and earn Bitcoin by participating in Stacking._

**Comment by markmhx** [comment]
That last suggestion works for me 👍
