### ISSUE TITLE
Same exact seed phrase with leading capital letters brings back a different wallet address

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#238]
**Describe the bug**
Enter the same exact seed phrase but capitalize the first letter the wallet will open up a totally different address

**To Reproduce**
1. Copy your seed phrase paste it into text box with no leading capitals
2. Login and record the address
3. Enter your seed phrase with leading capital letters
4.  Login and record the address
5. The two addresses do not match this is a P1 bug

**Expected behavior**
The wallet address should not change if the user has a capital letter on there seed phrase

**Screenshots**
<img width="1017" alt="Screen Shot 2020-09-15 at 11 33 27 AM" src="https://user-images.githubusercontent.com/49165468/93232243-ad45e880-f747-11ea-9a0d-93c3853bb16c.png">
<img width="1023" alt="Screen Shot 2020-09-15 at 11 33 08 AM" src="https://user-images.githubusercontent.com/49165468/93232247-adde7f00-f747-11ea-9673-24e094570447.png">
<img width="1012" alt="Screen Shot 2020-09-15 at 11 32 42 AM" src="https://user-images.githubusercontent.com/49165468/93232251-af0fac00-f747-11ea-84db-a2b29e75fdb7.png">
<img width="1022" alt="Screen Shot 2020-09-15 at 11 32 18 AM" src="https://user-images.githubusercontent.com/49165468/93232256-afa84280-f747-11ea-9c07-67f405e60f3f.png">

**Comment by kyranjamie** [comment]
I was blissfully unaware of this, but looking into it, I believe this is expected behaviour. [The BIP39 spec](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) doesn't specify how it should treat varying case. Further

> To create a binary seed from the mnemonic, we use the PBKDF2 function with a mnemonic sentence (in UTF-8 NFKD) used as the password

Which would indeed result in a different key/address. Given this, I don't think I should sanitise the seed with a `toLowerCase()` etc.

Assigning @jasperjansz as we may want to annotate this behaviour. 

@timstackblock same behaviour in the cli as well, you can pass a phrase argument to `make_keychain` to test this.

**Comment by markmhx** [comment]
@timstackblock how is this behavior handled in the current wallet? Do we force lower case?

**Comment by timstackblock** [comment]
Lower case is enforced


<img width="831" alt="Screen Shot 2020-09-16 at 8 12 24 AM" src="https://user-images.githubusercontent.com/49165468/93336380-b1304400-f7f5-11ea-82a1-1ece91ded200.png">

**Comment by markmhx** [comment]
To be resolved with https://github.com/blockstack/stacks-wallet/issues/239
