### ISSUE TITLE
"I have a Trezor wallet" link

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#248]
![image](https://user-images.githubusercontent.com/1618764/93581553-9995be80-f9a1-11ea-840b-8bb3db731344.png)

We need to consider where this will lead.

Options:
1) @markmhx a section of the website?
2) @ryanarndtcm a support page?

**Comment by markmhx** [comment]
I imagine we can add a section or page to the new Stacks Wallet section of blockstack.org here: https://www.blockstack.org/p/stacks-wallet

@ryanarndtcm might you want to help us research and draft the content needed here for Trezor users to port their keys either over to a Ledger device or software mode?

**Comment by markmhx** [comment]
We can adapt the same guidance found here: https://docs.blockstack.org/stacks-wallet/usage#trezor-wallet-support

**Comment by yknl** [comment]
The language looks good to me

**Comment by kyranjamie** [comment]
Any reason not to link straight to the website @markmhx? We'd then be maintaining two copies of the same content.

**Comment by markmhx** [comment]
I'm hoping we can actually keep as much documentation or instructions off websites in general, to keep everything in one place client-side and reduce dependencies. I don't imagine we'd copy this particular guidance to any website.

**Comment by kyranjamie** [comment]
I mean the **docs** website, sorry. So to keep it all there, rather than have duplicates between the docs & the wallet code.

**Comment by markmhx** [comment]
Right, I mean we don't plan to have these on docs either.

**Comment by kyranjamie** [comment]
I don't follow. This seems against the aim of having unified docs.

Where would we link someone that, for example,  asks support or in Discord "Can I use my trezor with the new wallet?". 
We can say "No" of course, but it would be nice link them to more info that doesn't first requirement to download and install the wallet.

**Comment by markmhx** [comment]
Generally speaking, we're looking to remove user-facing documentation from http://docs.blockstack.org/ per @agraebe's plan.

In that scenario, I'd suggest we simply tell users on Discord that they open up to the wallet and select the informational option. Presumably anyone who's already run into this as a problem and is seeking help has the wallet installed already. If we design this right, as well, the option should be clear enough in the UI to catch their attention before they have to seek out the same information via Discord.

**Comment by agraebe** [comment]
I think there are two important questions here:
1. should we have user-facing docs? (@markmhx would like to avoid that)
2. where should user-facing docs be hosted? (I would like it to in outside of technical documentation)

As for 1: I think there will always be a need for user-facing docs for any app. Designing it as self-explaining as possible will reduce the need, but it won't get to 0. Users could always have more general questions that don't fit on a UI or would distract from the main user flow. Adding all possible questions would blow up the scope for the app and make it hard to change. So, a link out to some user-facing documentation makes most sense IMHO

As for 2: User-facing documentation and technical documentation are vastly different in nature due to the goals. One is to ensure someone can complete tasks inside an app (very visual, simple/non-technical language, narrowly scoped). The other one is to transfer knowledge that developers can apply to build an integration (lots of code, very technical, connected to other content like references etc). If we simply ignore that and add user-facing docs pages into our current technical documentation, it'll rather create more questions and frustration for end-users. For developers, it'll be confusing due to the expectation in terms of language and content. If we were to do a unification of docs in terms of adding target audiences, I would suggest having clear separation (own category, different/simpler navigation, different language, maybe even a slightly different UI to indicate one is looking at a different space inside the docs).

To fix the issue and hand, while working towards a better solution, I'd propose we leverage the stacks wallet page to host user-facing documentation (including the FAQs). It has a narrow scope, the webpage is already tailored towards end-users, and with Sketch, it'll be easy to make content changes without having to update the app. It will also provide us with links that can be used from within the UI.

As a side note, it would also be preferable to move https://docs.blockstack.org/stacks-wallet/ content to the wallet page. We left and updated the content simply because there's no other place for it that allows us to make changes quickly. The current website (as I understand) would require engineers to make content changes and we didn't seem to want to touch it.

**Comment by markmhx** [comment]
As discussed yesterday during the planning meeting, I'd like to take all existing FAQs under the wings of UserX, considering them the right web-based vehicle for any user-facing instructions, either for the wallet or other products with UX like Connect. 

Accordingly, I've published this content at https://www.blockstack.org/questions/how-do-i-use-my-trezor-device-with-the-stacks-wallet, which can be linked from the wallet here.

cc @ryanarndtcm

**Comment by diwakergupta** [comment]
@markmhx @agraebe pretty much all the links in this issue no longer work :(

Broken:
- https://docs.blockstack.org/stacks-wallet and https://docs.blockstack.org/stacks-wallet/usage#trezor-wallet-support
- https://www.blockstack.org/questions
- https://www.blockstack.org/questions/how-can-i-use-my-trezor-device-with-the-stacks-wallet works but is impossible to discover (doesn't show up in docs search, not linked from old or new wallet)

**Comment by agraebe** [comment]
I just checked the docs redirects:
- `/stacks-wallet` is listed https://github.com/blockstack/docs/blob/master/next.config.js#L298
- `/stacks-wallet/usage` is listed https://github.com/blockstack/docs/blob/master/next.config.js#L287

@aulneau - is there an issue with the redirect implementation or are we not configuring it correctly?

**Comment by aulneau** [comment]
There is a bug I reported to vercel for this, it's within next.js itself. I am working to try and resolve it now.

**Comment by markmhx** [comment]
I've reopened https://github.com/blockstack/docs/issues/879 and assigned to @aulneau for better visibility here.

**Comment by aulneau** [comment]
Fix being deployed now :) should be live shortly -- had to bump next.js up to a newer canary version.
