### ISSUE TITLE
Blockstack Transaction still invalid after 1 week 

### ISSUE THREAD

**Issue by ameen0811** [blockstack/stacks-wallet#430]
Hello I have a blockstack transaction still invalid after one week. The recipient and senders addresses are all correct

**Comment by castadream2** [comment]
Same. Others have had the same. It was closed here https://github.com/blockstack/stacks-wallet/issues/115 as it was assumed self resolving, but it has not for others, and for me it has been 10 days. 

Received Stacks has "Invalid" tag after it for 6699.316 STX
_Sender_: SP3WV3VC6GM1WF215SDHP0MESQ3BNXHB1N6TPB70S
_Recipient_: SP2SM4WBD1VP7DTKNNZKPWKPX7TJDVP2CFWK51XK
_Transaction_: 2681c3c78c6867928a3a136dad81e5569cf2c1245c168e52058fa9e4d407ca74

**Comment by ameen0811** [comment]
Yea they should not have closed the issue/post. Especially for a sizeable amount. That is exactly what mine looks like. I have tried joining the discord from the blockstack website but have not had any luck. I think someone from the community discord could probably help us resolve this.

**Comment by markmhx** [comment]
Sorry you've encountered this problem. Due to recent increases in the value of BTC (which is used to pay for STX transaction fees on Stacks 1.0, as those transactions originate from exchanges or elsewhere), STX transactions may not settle unless BTC fee amounts are increased.

Unfortunately there's nothing we can do on our end to increase those amounts for 3rd party wallet providers. Please contact your relevant exchange or 3rd wallet provider with a request to resend your STX transaction with additional BTC, which may be necessary even if the initial BTC attempted to pay for the transaction has settled on the Bitcoin blockchain successfully.

Note that BTC will be removed from covering transaction fees soon as part of Stacks 2.0 Mainnet release, at which point STX itself will be used to pay for fees and these problems related to BTC volatility should be resolved. Please read about Stacks 2.0 timing [here](https://blog.blockstack.org/stacks-2-feat-complete-dec-15/).

**Comment by ameen0811** [comment]
So it looks like this is something that can’t be resolved because exchanges are not willing to resend the transaction.

**Comment by ameen0811** [comment]
So I reached out to Kucoin and they said the transaction is showing complete on their end. They said they will not resend the transaction and insisted I talk with someone at blockstack support to resolve the issue. So both sides are saying there’s no way to recover our STX? Seem fine

**Comment by ameen0811** [comment]
Ok update here. Today I received my STX after 13 days, I reached out to Kucoin twice and they created an additional support ticket. I am unsure if they resent the transaction but I am assuming they resolved the issue because they said they would be looking further into the issue. I did copy and paste what markmhx posted here above and sent that to the exchange to help them understand what went wrong. If anyone has this ‘invalid’ transaction in their stacks wallet. I recommend showing them marks response here to help them further assist you. Thank you Mark

**Comment by markmhx** [comment]
@ameen0811 I'm very glad to hear that! Thanks for following up here with the latest.

**Comment by clemons7778** [comment]
i am new to blockstack and looking to transfer my stx tokens to OKcoin.  i originally bought the stx tokens on binance but since I am in the US they sent me a message saying I had to remove them from my wallet or I may be locked out of my account.  i was able to sent the stx tokens to the native blockstack desktop wallet connected to my ledger and the balance transferred seems to be correct.  Though, I am having the same issue with the confirmation showing invalid.  i know i have a seed phrase written down for one of my stx wallets but i am not sure if when i set the destkop blockstack wallet up it was the same wallet as the wallet i have the seed phrase for.  my questions are: 

1. is there a way for me to verify the seed phrase by setting up a new blockstack wallet elsewhere to see if the desktop wallet with my stx balance is indeed the only stx wallet i have?  i don't feel comfortable resetting my desktop wallet until i know for sure i have the correct seed phase.

2.  how do i know which version of the desktop wallet i have?  there is no version indicator that i can find.

3. since my desktop stx wallet shows a balance even though the only receiving transaction i have shows invalid, what happens if i try to send those stx tokens to my OKcoin wallet?

Thank you all.  Sorry for not quite understanding all of this yet.  I'm trying!

**Comment by markmhx** [comment]
@clemons7778 Please see the note here in regards to exchange withdrawals: https://www.hiro.so/questions/what-known-issues-are-currently-affecting-the-stacks-wallet

Per question 1, each seed phrase will map to a STX address that you can use to compare various phrases. Open the "Receive" modal to see the address and compare it to the address shown elsewhere where you've entered a seed. It will be the same address if it's the same seed.

Per 2, this should be available under the "About Stacks Wallet" as an option in your operating system menu bar when the app is open.

Per 3, if the transaction is shown as invalid, any transaction you initiate to send those tokens elsewhere should fail since the invalid transaction amount hasn't been credited to your address successfully. You'll have to work with Binance to send another (successful) transaction before initiating a transaction to OKCoin.

**Comment by markmhx** [comment]
I'm going to close this issue since as noted in the link above, current invalid transaction issues appear generally related to Stacks 2.0 integrations on the side of exchanges. Please contact your relevant exchange if you've been unable to withdraw from it.
