### ISSUE TITLE
Display total, unlocked and locked balances

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#453]
Display in the wallet the correct balances when considering the vesting schedules. 

Input would be appreciated as to how these should be displayed.

**Comment by markmhx** [comment]
If I recall correctly, we had three main concerns about supporting locking schedules when we considered them for v4.0.0 a few months ago:

1. Naming collision given the newly introduced use of "locking" for Stacking UX within the wallet, and inability to come up with clear alternative
2. Creation and maintenance of code for functionality that will "self resolve" automatically towards the end of 2021
3. Additional workload in face of aggressive launch schedule

Our decision at the time was to fall back on not showing locking schedule information in the Wallet, leaving such information perhaps to the Explorer (though I don't know if we've addressed this with new Explorer, just the old) and throwing generic transaction errors for anyone who attempted to send more STX than they had unlocked.

I'm happy to revisit this decision, however, since users with locked balances will certainly appreciate their distinction in the UX. I sense, however, that this will take some design and development cycles that will push us past mainnet release, so we may want to consider it for v4.1.0. 

One way to resolve the naming collision issue is to simply lump all locked STX – regardless of cause, Stacking or otherwise – together in the UX e.g. under the total balance. The effect is the same in that context. However, we may need to describe the difference if we link the user to more information, presumably on the Explorer, that lays out their full unlocking schedule (as we do on the old Explorer).

**Comment by markmhx** [comment]
Note as well that we'd likely want to tackle this alongside the standardized balance component per https://github.com/blockstack/ui/issues/74

**Comment by markmhx** [comment]
This will be powered by the blockchain API via https://github.com/blockstack/stacks-blockchain-api/issues/423

**Comment by jasperjansz** [comment]
Total = Available + Stacked + Locked.

My suggestion would be to change "total balance" in the Wallet to "available balance":
![image](https://user-images.githubusercontent.com/25477905/108089572-0c52b500-707a-11eb-89eb-d7437f51157e.png)

The wallet shows Available and Stacked (in the card on the side). The locked is not that interesting in the wallet context as you can't use it. The minority that wants to see their locked STX (unvested from the token sale) can go to the Explorer where we have the full breakdown and schedule. That way we don't have to change our Wallet UI to accomodate them.

**Comment by markmhx** [comment]
Example for reference from a wallet currently Stacking:

![image](https://user-images.githubusercontent.com/28991/108095308-0364e200-7080-11eb-9fc7-bc28e33feb4f.png)

![image](https://user-images.githubusercontent.com/28991/108095323-05c73c00-7080-11eb-868d-8ed725629410.png)

**Comment by jasperjansz** [comment]
Latest: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=4736%3A7

Below the total shows locked/available. Locked = stacking + locked from token sale.

Also suggest we move the "view on explorer" link to the top right to make this component less cluttered.

**Comment by kyranjamie** [comment]
That does look better, but consider if there's an update available, in testnet mode, and there's a narrow window frame.

**Comment by jasperjansz** [comment]
@kyranjamie I see in the Testnet wallet you hide the testnet indicator below a certain width. I think we can extend that approach to the menu items. If it becomes too narrow we can show a menu icon instead of the items: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=4779%3A28289

**Comment by markmhx** [comment]
Closing since vesting schedules end next month so this will no longer be relevant.
