### ISSUE TITLE
Add "Pending Ledger review" guidance to UI

### ISSUE THREAD

**Issue by ades5** [blockstack/stacks-wallet#539]
i am unable to open my stacks wallet.  I open the stacks wallet and then sign in on my ledger device.  when i open the stacks app on the device, the device display reads "pending ledger review".  please advise on why i am getting this notice and / or how to move past it.

**Comment by kyranjamie** [comment]
Does pressing both the buttons on the Ledger let you proceed?

**Comment by markmhx** [comment]
I spoke with @ades5 about this live, and the double press did indeed solve this issue for him.

However, I think the UI could benefit from guidance that instructs users to do this upon seeing "Pending Ledger review" since the interaction isn't altogether clear and until the Stacks app is taken out of "developer mode" in Ledger Live.

This could be as simple as adding a line `Double press the top two buttons on your Ledger device simultaneously when it displays "Pending Ledger review"` below "Open the Stacks app" copy here:

![image](https://user-images.githubusercontent.com/28991/105066628-4763c780-5a7f-11eb-9d35-471065c3bc91.png)
