### ISSUE TITLE
Trigger address confirmation on Ledger in receive modal

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#548]
Ensure the STX address is visible on **both** the Ledger and Stacks Wallet at the same time.

<img width="514" alt="Screen Shot 2021-01-20 at 12 12 12" src="https://user-images.githubusercontent.com/28991/105176887-299d6d80-5b26-11eb-9ef7-e6b12325c5ce.png">

**Comment by trevismd** [comment]
Hi team stacks-wallet,
I'm very excited about the project. However, this issue had to be upped. I'm surprised it's been here for over a month.
I wanted to point out that misinformed people could quickly "validate" the address without actually verifying it (because it would require copying it to paper, for example) and so, while you work on it, I think connection with Ledger should not be allowed or with `strongly highlighted recommendations` as long as this ~~enhancement~~ requirement is not implemented. 
Because with the stacking incentive, some people may overlook this. It's bad press, but it would be worse in case of hacks. Just my 2 cents.

**Comment by kyranjamie** [comment]
Hi @trevismd,

I'm not sure I totally follow. We've added to the wallet the requirement that, when viewing your Ledger address via _Receive_, you **must** confirm the address with the device itself. This is to avoid the circumstance whereby the address is changed on a compromised machine, in an attempt to trick a user.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/1618764/109697882-105cf780-7b8f-11eb-814a-ff6f9fbc78d6.png)

</details>

We may also require the device's address to be confirmed first when sending a transactions. However this is less important (if you used a different device, or sender address was manipulated maliciously, the tx would fail).

Why do you think it is necessary to disable Ledger functionality? This would lock many users out of their funds, and push users towards less-secure software wallets.

**Comment by trevismd** [comment]
When getting to step 3, the receiving address should be visible on desktop screen **while** also showing on ledger, in order to compare the two (as in ledger live). In my new installation of latest stacks-wallet version however, it is not the case. It shows first on ledger, asking to approve ... nothing since I cannot compare anything (receiving for the first time). 
Then, if I do approve on ledger, an address appears on stacks-wallet and offers me to copy it but it is not visible anymore on ledger. So I would have had to copy the address earlier to confirm they match.
If it is a bug I'll "file" it as such.
About consequences, I agree with you, and suggested strong warnings for current users in the meantime.

**Comment by kyranjamie** [comment]
Ah, I see. You're right they should be visible at the same time. Thanks for the feedback.

We're not able to add a warning without updating. But this is a simple change, so we'll just include this fix in the next version.

**Comment by markmhx** [comment]
@kyranjamie can you move this onto the kanban board?
