### ISSUE TITLE
[4.0.4] Bug: after install the latest stacks desktop wallet, I lost my previous wallet

### ISSUE THREAD

**Issue by xinster** [blockstack/stacks-wallet#576]
Bug found testing Stacks Wallet build undefined, 4.0.4.

**Comment by markmhx** [comment]
This is expected behavior since the old / previous wallet is no longer recommended for usage. The new wallet does everything the old one did plus can send STX on Stacks 2.0, whereas the old one's sending capabilities were disabled against Stacks 1.0.

Note that if you've overwritten the previous wallet, you have **not** also overwritten any key stored in memory since the old wallet never stored keys or seed phrases in memory.
