### ISSUE TITLE
Factor pending transactions into balance and "Send Max" calculation

### ISSUE THREAD

**Issue by RyWalk** [blockstack/stacks-wallet#591]
I used the Hiro Wallet 4.0.4 to send a tx and used the "Send Max" button. The transaction ended up stuck in the mempool with the reason being "Insufficient Balance". It looks like the wallet didn't calculate the appropriate fee... instead it sent the max funds without subtracting the expected fee first. I'm not a dev so don't know if these details are helpful, but id just moments earlier submitted a smaller tx from the same wallet that worked and confirmed just fine. I was also sending this from a ledger. Not sure  if those details help.

**Comment by markmhx** [comment]
Thanks for this report. Mind providing the transaction ID itself so we can look it up on the Explorer and investigate?

**Comment by RyWalk** [comment]
Hey Mark. Tx ID 0x6224cafa616d0bed7bf3b870d733678180f858163810d7f474129ac6332ba2fd

**Comment by markmhx** [comment]
I see, it appears that the wallet needs to account for pending transactions when calculating the maximum for "Send Max" since that first transfer of yours brought down the effective available balance to 119,998.982 STX, which is less than the 119,999.99982 STX you subsequently attempted to transfer (with or without additional fees of 0.0018 STX).

https://explorer.stacks.co/address/SP370A61W0RD9ZBK23Q34YQAZX0BE5NW8V8XW264G?chain=mainnet
https://explorer.stacks.co/txid/0x7f809f62ef37883f31f60c6bd453cfbfedf2c7ebe6ab0cc9c875222de3038503?chain=mainnet

**Comment by markmhx** [comment]
I tested this by first sending 1 STX then sending another with "Send Max". The total balance immediately showed the negative value of the first transaction instead of 0 STX (or simply the current balance without taking account into either pending transaction):

<img width="602" alt="Screen Shot 2021-03-26 at 13 30 11" src="https://user-images.githubusercontent.com/28991/112631793-9d663a00-8e37-11eb-82d5-9114d2ae4f74.png">

**Comment by markmhx** [comment]
I appear to be still running into this bug while testing v4.1.2:

1. Starting balance is 153,936,001.999619 STX
2. I send 1 STX, which is 1.00018 STX with fees
3. I immediately send with "Send Max", calculated as 153,936,001.999439 STX, which is 153936001.999619 STX with fees

Address: https://explorer.stacks.co/address/ST1SCZCYS2PPRJWCHFHCBATEXSC4N9NTYN9TZBMTQ?chain=testnet

<img width="602" alt="Screen Shot 2021-03-26 at 13 30 11" src="https://user-images.githubusercontent.com/28991/112633357-8d4f5a00-8e39-11eb-8995-3c0f66f47195.png">

**Comment by markmhx** [comment]
Here's an interesting side effect: while these two transactions are still pending, I get "insufficient balance" for the Stacking delegation option but not for the direct one:

![image](https://user-images.githubusercontent.com/28991/112634542-03a08c00-8e3b-11eb-8652-a1f07163dca1.png)

Should I open a separate bug issue for this?

**Comment by markmhx** [comment]
This worked for me while testing with the latest build by sending two STX transactions in succession, the latter with "Send Max":

![image](https://user-images.githubusercontent.com/28991/113289605-b6b42e00-92f0-11eb-9e30-6c7d0c268ebb.png)

**Comment by markmhx** [comment]
It also worked by initiating delegation and sending one STX transaction with "Send Max" in succession, though oddly the delegation activity item is showing up before the sending one?

![image](https://user-images.githubusercontent.com/28991/113290589-2971d900-92f2-11eb-8bf7-d0a5c78a87ec.png)
