### ISSUE TITLE
Add guidance around memos for users interacting with exchanges

### ISSUE THREAD

**Issue by gSaenzt** [blockstack/stacks-wallet#593]
Hi there
Perform the installation of wallet stacks in my ledger x, following the steps in the previous answer. This was successful.
However I want to withdraw STX from binance to my stack wallet, for which I need my address and MEMO, but the stack wallet app only loads the address. DOES NOT charge the QR or MEMO.

What I can do?

**Comment by markmhx** [comment]
The memo is something you'd enter manually into _Binance_ when sending STX from Binance to your Stacks Wallet. It will appear in the Stacks Wallet upon receipt there, but it's not a value that the Stacks Wallet provides.

**Comment by gSaenzt** [comment]
Hello markmhx, thanks for your answer.

Suddenly I explained well what my problem is.

I have STX on Binance and to take it to my wallet I need my address and the memo, but the stacks wallet app does not deliver the memo, when I make the query.
attached [image[](url)](url
![Captura](https://user-images.githubusercontent.com/72468980/106949952-b38b3000-66fb-11eb-9865-d717eee06887.PNG)
)

**Comment by kyranjamie** [comment]
@gSaenzt You don't not need to set a memo _to receive_ STX, only a correct address.

**Comment by gSaenzt** [comment]
@kyranjamie Thanks for your answer, but binance warns that if it is not supplied in MEMO or if it is incorrect, you run the risk of losing funds.
at the moment the withdrawal is disabled, for this I do not share an image

**Comment by fluidvoice** [comment]
> @gSaenzt You don't not need to set a memo _to receive_ STX, only a correct address.

I think it will avoid confusion of users to include a comment/instruction on the **Recieve STX dialog** telling them to include any short identifying phrase in the memo field if the wallet or exchange they are using to send requires it.
Users get confused when exchanges enforce using the memo field when sending but the wallet does not give/display one.

**Comment by markmhx** [comment]
We could certainly add guidance here to help clarify things where memos are concerned.

I'm a bit confused though whether / why Binance is insisting on a memo when _withdrawing_ (Binance -> Stacks Wallet) since I've personally only seeing this requirement in their UI for _depositing_ (Stacks Wallet -> Binance).

@gSaenzt Mind providing a screenshot of Binance's messaging here when withdrawing is enabled again and you have an opportunity?

**Comment by gSaenzt** [comment]
@markmhx  Since I made my last post, binance has suspended withdrawals, that's why I have not uploaded a screenshot .. I also did not make the withdrawal, although the message in the Binance wallet is clear, If the user does not enter the MEMO or MEMO is incorrect you may lose funds.
when withdrawals are enabled again, upload the capture.

**Comment by gSaenzt** [comment]
This is a currently message.
![Screenshot_20210214-131209](https://user-images.githubusercontent.com/72468980/107885151-a3770b80-6ec6-11eb-8370-e11f81de5b6d.png)

**Comment by gSaenzt** [comment]
![Uploading Screenshot_20210217-055058.png…]()

**Comment by gSaenzt** [comment]
![Screenshot_20210217-055047](https://user-images.githubusercontent.com/72468980/108228887-43be7180-710d-11eb-839c-3dec033387e1.png)

**Comment by gSaenzt** [comment]
@markmhx @kyranjamiethis is the message with which binance warns that if a Nemo is not written, the resources may be lost.

**Comment by markmhx** [comment]
I see the problem now. This appears to be the same confusion as reported on https://github.com/blockstack/stacks-wallet/issues/571 wherein exchanges show generic instructions for including a memo when withdrawing, regardless of the destination (and whether or not it actually requires a memo, which the Stacks Wallet does not).

I'm closing this issue simply because we're already handling its solution on the other one linked above. Thanks @gSaenzt for this additional information 🙏  Rest assured that you can proceed to withdraw from Binance to the Stacks Wallet directly without adding any memo. It's only when you send to an _exchange_ that this the memo is normally needed.
