### ISSUE TITLE
I can successfully delegate with 50,000,000 STX but they do not lock. 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#613]
I can successfully delegate with 50,000,000 STX but they do not lock. This may not be a wallet bug but I would like confirmation on why this is happening

I have not seen delegated STX that are below the stacking threshold number 86,000,000+ actually locked in the wallet. I see all the contract calls go out but the last 2 fail.

The last 2 contract calls do not fail if the amount of STX delegated is over 86,000,000.

Step 1 Delegate 50,000,000 STX (stacking threshold on staging is 86,000,000+)

CONTRACT CALL GENERATED: delegate-stx
https://explorer.stacks.co/txid/0xcc671198079ab8b7bf4d6ab07758a941c3cec63b09dce9db2e5431959e27facb?chain=testnet

Step 2 Run delegation scripts

CONTRACT CALL GENERATED: delegate-stack-stx 
https://explorer.stacks.co/txid/0xdbfb0e0aa0baea1edcf2516bd303d1fdd0017e27c85e9949abc4f6b9a846cdf6?chain=testnet

Step 3 Verify locking happens in the wallet for delegated STX

CONTRACT CALL GENERATED: stack-aggregation-commit
https://explorer.stacks.co/txid/0xd283176806418ed74a321a418085088231a22056c61e36c44057a2f29345ef6d?chain=testnet

**Comment by kyranjamie** [comment]
In this test scenario, there's only 1 delegatee delegating below the minimum. Thus, the delegator cannot `delegate-stack-stx`.

To test delegating below min, you'll need a second address that also delegates STX to bring the total amount delegated above the min. threshold.

Perhaps someone else can elaborate more clearly than this, but afaik this is expected behaviour.

**Comment by markmhx** [comment]
I imagine @jcnelson would have some input here given his work on this function, though I suspect it's not a client-side wallet bug in any case.

**Comment by timstackblock** [comment]
Thanks @markmhx  I will close this issue as it is a non blocker for the wallet release

**Comment by timstackblock** [comment]
@kantai please review my contract calls above and see if anything seems like a major issue

**Comment by kantai** [comment]
> In this test scenario, there's only 1 delegatee delegating below the minimum. Thus, the delegator cannot `delegate-stack-stx`.
> 
> To test delegating below min, you'll need a second address that also delegates STX to bring the total amount delegated above the min. threshold.
> 
> Perhaps someone else can elaborate more clearly than this, but afaik this is expected behaviour.

I can't see the testnet transactions mentioned in this issue, but if it is what @kyranjamie describes, then yes, that is expected behavior.

**Comment by timstackblock** [comment]
I delegated 2 wallets (2 delegatees) both at 50,000,000 STX for a total of 100,000,000 stx.

The wallets address for both are 
STZ0HRKCKTBQS7X712MJ6QMH7R1MVD8EX8EN9Q2M 
STW4X0YSV5H1Q4DKJTBKM99N3ZPTYR1PQ4CCGV6T

Testnet is down but as soon as it comes up I can put links to the transactions, because there were 2 wallets with the total amount delegated = to 100,000,000 stx I expected this to work.

**Comment by kantai** [comment]
Looking at the testnet logs, it seems like the `delegate-stack-stx` transactions didn't succeed:

```
    Handle special-case contract-call to QualifiedContractIdentifier { issuer: StandardPrincipalData(ST000000000000000000002AMW42H), name: ContractName("pox") } delegate-stack-stx (which returned Response(ResponseData { committed: false, data: Int(22) }))
```

Indicates the `delegate-stack-stx` call returned an `(err 22)`.

**Comment by agraebe** [comment]
(I cannot review the actual txs, but providing my input based on my current understanding)

The error above is thrown here: https://github.com/blockstack/stacks-blockchain/blob/master/src/chainstate/stacks/boot/pox.clar#L585. This indicates that the delegated amount you set in the wallet is lower than the amount you're trying to stack with the `delegate-stack-stx` method. This might be due to tx fees?

> > In this test scenario, there's only 1 delegatee delegating below the minimum. Thus, the delegator cannot `delegate-stack-stx`.
> > To test delegating below min, you'll need a second address that also delegates STX to bring the total amount delegated above the min. threshold.
> > Perhaps someone else can elaborate more clearly than this, but afaik this is expected behaviour.
> 
> I can't see the testnet transactions mentioned in this issue, but if it is what @kyranjamie describes, then yes, that is expected behavior.

I don't think this is right - I reviewed the comments and implementation of `delegate-stack-stx` (https://github.com/blockstack/stacks-blockchain/blob/master/src/chainstate/stacks/boot/pox.clar#L560) and there is _no_ minimum STX amount check. Meaning, a delegator can call this method with, let's say, 10K STX for every single user successfully. The tokens would be locked for the users, but the delegator couldn't call the `stack-aggregation-commit` method successfully if all committed tokens (from all users) don't meet the minimum threshold.

**Comment by timstackblock** [comment]
We just figured out the problem it's not a bug. The issue is the test script that is making the delegation-stack-stx contract call and passing in the STX amount `  const amountMicroStx = new BN(poxInfo.min_amount_ustx).add(new BN(100000));`
The value being passed is to high which is causing the contract call failure, this would not happen in production.
