### ISSUE TITLE
Unable to transfer funds from wallet - block explorer inconsistency  

### ISSUE THREAD

**Issue by krupda42** [blockstack/stacks-wallet#663]
Greetings, 

This is going to be a bit messy so bear with me. 

In December I purchased STX via Binance and sent them to my Stacks Desktop Wallet.

When I created said Stacks Desktop Wallet, I was never given a wallet seed - it went straight to the wallet interface after I accepted the terms and conditions.

I am now trying to transfer STX out of the wallet and am unable to do so. I event sent around 150$ worth of BTC to pay for the transfer fee since I thought that was the initial issue. 

When I try and send, it asks me to connect my Trezor which is strange because I did not use my Trezor to set up the wallet. 

In any case, the Stacks Wallet does not seem to detect the Trezor device, and is stuck loading (see image below). I also just read on the website that the Trezor wallet is no longer supported as a means of transferring funds. 

The problem is I have no wallet seed, so I can't reset the wallet. How can I get these funds out? Is there a way to so? 

Any help would be much appreciated, because it will really suck to lose these funds. 

A few images below. Note that my wallet balance and history is quite bizarre in the Stacks Explorer. 

![Wallet Balance](https://user-images.githubusercontent.com/79975899/109796591-572a0c00-7be6-11eb-9558-d3afdc1b0654.PNG)

![Continue](https://user-images.githubusercontent.com/79975899/109796625-601add80-7be6-11eb-81e0-a46f5c78a535.PNG)

![Connected](https://user-images.githubusercontent.com/79975899/109796633-63ae6480-7be6-11eb-943f-01c7e8818ea3.PNG)

![Inconsistent](https://user-images.githubusercontent.com/79975899/109796719-82146000-7be6-11eb-9a7b-6a15b23302ba.PNG)

**Comment by markmhx** [comment]
@krupda42 were you able to resolve your issue here by upgrading to the newest wallet? https://www.hiro.so/wallet/install-desktop

**Comment by krupda42** [comment]
> @krupda42 were you able to resolve your issue here by upgrading to the newest wallet? https://www.hiro.so/wallet/install-desktop

Hey Mark, yes I was. Got help through the Telegram channel. Thank you so much!

**Comment by craigusr** [comment]
Hello I have a similar issue. I have Stacks v 2.0 which shows a balance.

I tried the newest wallet and entered the recovery seed, but it shows zero balance in the new wallet. 
I'm not 100% sure that is the correct seed as I was having issues and I think I reset the wallet once.

Anyway is there a way to extract funds out of the old Stacks 2.0 wallet somehow if you don't have the seed?

It is asking for a Ledger device and I don't remember doing anything with that previously.

Thanks for any suggestions.

**Comment by craigusr** [comment]
![image](https://user-images.githubusercontent.com/12520215/110265592-c8641900-7f70-11eb-8491-d33a75457f4b.png)

**Comment by markmhx** [comment]
@craigusr If it's asking for a Ledger device, that's evidence that one was previously connected to the older wallet for authentication. Have you tried connecting the Ledger device you have on hand to the new wallet to see if your balance shows up there?

**Comment by craigusr** [comment]
Hi Mark, The problem is the new wallet wants a recovery seed which I do not appear to have, my bad. I'm pretty sure that the old wallet was never hooked to a Ledger so not sure why it is asking for that.

So my question now is there a way to recover the tokens using the old wallet which shows a balance. I'm not clear if @krupda42 was able to do this without having a recovery seed? What is the telegram channel? I also have timed released tokens going to the address so at a minimum hopefully those tokens can go somewhere else as they are released in  the future :)

Thanks for any help,
Craig

**Comment by markmhx** [comment]
@yknl Is there any reason the wallet would prompt for Ledger when trying to send STX unless the user had previously authenticated with it?

@craigusr I imagine that @krupda42 may have been able to connect to the new wallet having migrated their recovery seed from their Trezor device per https://www.hiro.so/questions/how-can-i-use-my-trezor-device-with-the-stacks-wallet

There's unfortunately no way to connect to the new wallet without a seed, and there's no way to export or recover the seed from the old wallet itself since it never stored it in memory.

**Comment by yknl** [comment]
> @yknl Is there any reason the wallet would prompt for Ledger when trying to send STX unless the user had previously authenticated with it?

No the wallet won't switch from a software to hardware wallet without the user resetting it.

**Comment by craigusr** [comment]
I was a newbie back when I did this and I do remember resetting the wallet because nothing was showing up (no balance). I later learned that no tokens had been time released yet so that was normal. I don't remember doing anything with the Ledger, but I must have done something. I don't see any stx in there , is there a way to check if I somehow put them in the wallet?

The new Ledger software has STX as "experimental". How could it have worked before this?

**Comment by craigusr** [comment]
![image](https://user-images.githubusercontent.com/12520215/110376185-c00aed00-8007-11eb-9b5b-db79a7863e85.png)

Here is the balance showing up in the old wallet. I don't see anything in Ledger sw.

**Comment by craigusr** [comment]
Another STX in Ledger??

![image](https://user-images.githubusercontent.com/12520215/110378054-fea1a700-8009-11eb-8aeb-16853027af7f.png)

**Comment by markmhx** [comment]
@craigusr Your STX tokens won't show up in Ledger Live itself anywhere. And there is indeed another "STX" displayed in Ledger Live here (for StoxToken based on Ethereum), but it's an entirely different token.

Your last screenshot appears to be from the "Accounts" tab of Ledger Live, which doesn't have Stacks support in general. The only thing to do in Ledger Live for Stacks is ensure that you've installed the Stacks app on your Ledger device per the following instructions: https://www.hiro.so/questions/how-can-i-use-my-ledger-device-with-stacks-wallet

I suspect that your Stacks holdings are indeed held on your Ledger. Would you mind downloading [the new wallet](https://www.hiro.so/wallet/install-desktop) then following [the Ledger instructions](https://www.hiro.so/questions/how-can-i-use-my-ledger-device-with-stacks-wallet) to see whether your balance shows up there?

This new wallet will overwrite the older wallet you have installed already, but that's okay since the older wallet can't be used for managing your STX anymore in any case (and by overwriting it, there is no risk you'll erase your seed because, as mentioned above already, it doesn't store the seed in memory).

This new Ledger support is indeed "pending Ledger review". However, it's ready for usage now.

**Comment by craigusr** [comment]
FYI - I have resolved the issue the wallet was connected to the Ledger device, it was just difficult to figure out the correct steps. 

Some diagrams on how it works would be helpful!

**Comment by craigusr** [comment]
Thanks for your help.
