### ISSUE TITLE
Prevent delegation if user has currently locked STX balance

### ISSUE THREAD

**Issue by aamjad2001** [blockstack/stacks-wallet#664]
First of all revoking delegation is incomplete. after revoking stx delegation. the process is completed but wallet still says that the stx are locked.
secondly delegating stx after revoking gives this message when checking status ,for no reason and delegation fails
  This transaction did not succeed because the transaction was aborted during its execution.

https://explorer.stacks.co/txid/0x9d486598bd56de2ff370d8124f83ab2d051327d282211eec676d03a9fd3b8c55?utm_source=stacks-wallet&chain=mainnet
 
new here so sorry in advance if my reporting is not standard

Bug found testing Stacks Wallet build undefined, 4.1.0.

**Comment by aulneau** [comment]
> First of all revoking delegation is incomplete. after revoking stx delegation. the process is completed but wallet still says that the stx are locked.

Revoking delegation does not unlock your already stacked tokens. You can think of delegation like giving permission to an address to stack your STX. If you have given permission, and they have stacked them, revoking only prevents them from stacking them again.

> secondly delegating stx after revoking gives this message when checking status ,for no reason and delegation fails
This transaction did not succeed because the transaction was aborted during its execution.

It gives error code 3, which means your stx are already stacked:
![Screen Shot 2021-03-03 at 2 27 04 PM](https://user-images.githubusercontent.com/11803153/109867803-90856a80-7c2c-11eb-8c82-17c74938ec72.png)

![Screen Shot 2021-03-03 at 2 27 00 PM](https://user-images.githubusercontent.com/11803153/109867820-93805b00-7c2c-11eb-9dc0-96f8e53c5333.png)

**Comment by aamjad2001** [comment]
![stacking](https://user-images.githubusercontent.com/80005160/109899347-8b213200-7cb7-11eb-9277-708196add4f8.png)
i think the pic is self explanatory.
i stacked 270 stx. the process was successful but the link to stack/ delegate further stx was no more there. so i revoked the stx already stacked. 
the link reappeared but now this is the situation

**Comment by markmhx** [comment]
@aamjad2001 Is one "Failed to delegate STX" failed transaction showing here for every attempt to initiate delegation _after_ having revoked delegation one time?

@aulneau Does this mean that a user cannot initiate delegation whenever they have any number of STX currently locked / Stacking? That seems like a curious constraint, since why would initiation delegation as such interfere with the current lock or vice versa?

I'm updating this issue to handle this state better since it seems we should prevent the use of the delegation form if the user has a currently locked balance.

**Comment by aulneau** [comment]
> @aulneau Does this mean that a user cannot initiate delegation whenever they have any number of STX currently locked / Stacking? That seems like a curious constraint, since why would initiation delegation as such interfere with the current lock or vice versa?

I do believe that to be true unfortunately. It's the same as if you're stacking. You cannot stack 2 times at the same time from the same address. A delegatee who has had tokens stacked, is "stacking".

**Comment by kyranjamie** [comment]
I've noticed this myself today. The API returns that the user is stacked (such as when you've delegated, pool has stacked, and you've revoked), but the UI doesn't display the stacking progress.

**Comment by aamjad2001** [comment]
Is the issue solved?

**Comment by kyranjamie** [comment]
Yes, download the latest release https://github.com/blockstack/stacks-wallet/releases/tag/v4.1.1

**Comment by aamjad2001** [comment]
Thanks!
