### ISSUE TITLE
Visuals for pooling / stacking by yourself

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/stacks-wallet#726]
When a user starts stacking in the wallet they are presented with two options for how to start stacking:
1. Stack in a pool
2. Stack by yourself

A visual for each option would really liven up this screen and potentially help people understand the differences between both. I've added a placeholder spot above, but the shape/size of these is up to you as long as as the layout remains in tact.

Screen: https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-%F0%9F%92%BF-desktop?node-id=4998%3A34019

**Comment by kyranjamie** [comment]
Hover animations welcome.

**Comment by eugeniadigon** [comment]
Uploaded here https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-%F0%9F%92%BF-desktop?node-id=5067%3A35541

I also made two hover animation tests: https://readymag.com/u211830829/2722307/

_*I'd like to discuss what's the best way to share animations - I used readymag because it was the fastest for me but I can dig into Principle or Flow if that's preferred_

**Comment by markmhx** [comment]
So cool! ❤️

**Comment by kyranjamie** [comment]
These were handled in the stacking updates
