### ISSUE TITLE
Stacks Wallet for Desktop: Update Download Button 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/stacks-wallet#737]
The "Update Available" points to this page: https://www.hiro.so/wallet/install-desktop - the "DOWNLOAD" button incorrectly points to https://github.com/blockstack/stacks-wallet/releases/download/v4.1.1/stacks-wallet.mainnet.v4.1.1.dmg

Update to download the Hiro STX desktop wallet version 4.1.2: https://github.com/blockstack/stacks-wallet/releases/tag/v4.1.2 

Thanks to @qxotk sharing this in Discord! 🙏

**Comment by markmhx** [comment]
I just fixed the URLs manually. We still need to automate these URL updates with https://github.com/blockstack/hiro.so/issues/11, which we should do soon now that the build itself points to this install page instead of GitHub, making this an even greater priority / narrowing the manual update window.
