### ISSUE TITLE
Fix inability to confirm password for user on Windows 10

### ISSUE THREAD

**Issue by NV024** [blockstack/stacks-wallet#739]
Bug found testing Stacks Wallet build undefined, 4.1.2.

[4.1.2] Bug: <The Wallet can not accept the password . I have recovered my account several times from key but the password I am setting it into is not accepting . I have changed several time it is not accepting the password . I have updated it with latest version 4.1.2 and used older one also . Same error I am using Win 10 . Tried uninstalling and installing same no diffrence>

**Comment by kyranjamie** [comment]
@NV024 What error do you get when entering your password? Did the issue happen in 4.1.1 as well? 

With your Secret Key backed up safely on paper, can you reset your wallet and restore it?

**Comment by NV024** [comment]
Hi Blockstack/Stacks-Wallet,

I have my key safe tried several times with restore . Earlier used 4.1.0
then directly . To ,4.1.2 and no difference

**Comment by kyranjamie** [comment]
I need a little more info to work with.

As I understand, first the wallet won't accept your password? Does the wallet show an error? Are you sure you're using the correct password?

What happens when you try and restore the wallet with your seed phrase? This doesn't work either? This sounds like a separate issue from your password not working.

It's not clear if this is an issue that's introduced in `4.1.2`, or whether it existed in earlier versions?

**Comment by NV024** [comment]
Dear Blockstack/Stacks-Wallet

Lets say that I am reinstalling wallet again with my seed it is okey it
gets installed  . Then application ask me to set password then I set the
password its all okey . But when i try to send my stacks to any other
wallet address . I put the same password there and it shows error password
is incorrect .This problem i am facing as today even tried with new version
update still I am not able to do it.
May be i guess if it could be another issue i am assuming is it could be
that my old password once stored in setup is not getting erased is it like
that something i am suspecting about.

**Comment by kyranjamie** [comment]
Can you share a screenshot of what's happening when it rejects your password?
