### ISSUE TITLE
Unable to retrieve STX with only Trezor (no passphrase)

### ISSUE THREAD

**Issue by dlwjiang** [blockstack/stacks-wallet#782]
I'm wondering if anyone has the same issue I have. I've been trying to access my old stacks wallet which has been dormant for a year. I initially set it up with Trezor thinking it was secure that way and didn't take much precaution with the private key which I have lost.

I opened the old wallet and it showed me the now significant sum of STX but was unable to move money around as it would freeze when it asked for the Trezor.

I downloaded the new wallet and was disappointed to see that it has dropped support for Trezor and requires the original key phrase.

Does anyone know if I can get the phrase from the Trezor somehow? The key HAS to be on there in some form correct? Is there an older version of the stacks wallet I can use to access my funds through the Trezor.

Very disappointed that this kind of change was just without more community broadcast or a backwards compatibility solution

Thanks

**Comment by markmhx** [comment]
My apologies that this change in Trezor support caught you by surprise. 

As far as I'm aware, there is no way to extract the phrase from a Trezor device by design since otherwise it would present a security threat. It's critical that hardware device holders maintain a separate backup copy of their phrase at all times since the device itself is meant to be a convenience mechanism, not definitive storage / backup mechanism.

If you are able to locate the phrase as backed up somewhere, you can follow these instructions for using it either directly in the new Stacks Wallet or after migrating to a Ledger device: https://www.hiro.so/questions/how-can-i-use-my-trezor-device-with-the-stacks-wallet

We hope to add support for Trezor again in the future. However, it's contingent on the company's interest in working with us on the matter. So if you aren't unable to locate your phrase, you may need to hold onto your Trezor device until that point in time in which they're ready to work with us and we restore support, at which time you should theoretically be able to connect your Trezor and regain access to your STX that way.

Please let me know if you have any questions.

**Comment by dlwjiang** [comment]
Thanks Mark, it seems like a migration to ledger is the only way forward if I want access now.

To clear up terminology for posterity, it sounds like having the **recovery**-phrase would work since you can just copy-paste it into the stacks wallet secret-key input. However because my Trezor uses a **pass**-phrase there is no way to input both the recovery and the pass phrase without having a supported hardware wallet (Ledger)

Curious as to why the pass-phrase cannot be part of the input page in the STX wallet though. Given that it's possible to migrate from Trezor to Ledger, it should be an open protocol. Is it that BIP-39 somehow enforces that the passphrase has to connected to a hardware wallet?

**Comment by markmhx** [comment]
It may be possible to support the entry of a passphrase  directly in the wallet in addition to the Secret Key. However, we haven't prioritized the work to investigate or build this yet since it appears that Trezor users have generally preferred to migrate to Ledger instead of entering their Secret Key directly. However, we can certainly reconsider its prioritization if we learn of greater interest in this functionality!

**Comment by dlwjiang** [comment]
+1 to more support for more hardware wallets (or passphrase input support)! It's a bit of an awkward feeling for me as I sold my Ledger in order to not have to juggle so many things around. 

It is good to know that they seem to have more open support vs Trezor which sounds like their centralized approval is necessary for support though

Thanks again!

**Comment by markmhx** [comment]
Thanks for your understanding! And sorry about having to return to Ledger here. Hopefully we'll support both again soon. 🤞

**Comment by jindrichbartek** [comment]
Hi, I have the same problem except I don't use passphrase (25th word of seed). I've lost recovery seed, but I do have access to the Trezor. So I wonder how can I access my STX?

What if I download and build an old version of the wallet (v3.1.0). Will I be able to connect it with my Trezor and access the STX?

**Comment by markmhx** [comment]
@jindrichbartek The old wallet won't work anymore. Have you tried migrating to Ledger per these instructions? https://www.hiro.so/questions/how-can-i-use-my-trezor-device-with-the-stacks-wallet

**Comment by jindrichbartek** [comment]
Yes, but the problem is I don't have access to my Trezor seed. Likely, I've lost it. I do have access to the Trezor but I can not generate seed anymore.  Do you see any other solution?

Or is there at least a way how can I link my trezor to an STX wallet? So I am sure it's really a problem of the lost seed.
