### ISSUE TITLE
[4.2.0] Bug: Wrong Balance

### ISSUE THREAD

**Issue by Aschettini** [blockstack/stacks-wallet#810]
Hi there,

Bug found testing Stacks Wallet build undefined, 4.2.0.

The balance is wrong and does not corresponds to my actual balance , it is missing  277.78 stacks  ( the recurrent amount of deposit month by month ).

I started thus on the stacks offering which deposits started to be done on October 19th  2019 by the details indicated below:

Invested USD:	 $2,000.00 
Rate USD/STX	 $0.30 
STX:	 $6,666.67 
Months	24
Start Date	10/9/2019
STX deposit/Month	 $277.78 

Attached you have my screen shots of the balance on my account addr: SP1RPNBT99E1JA56P9TN4EYRN9KZ7YYVH05VBTNY1

Surprisingly on the explorer the amount is also wrong with those 277.78 stacks missing..

I hope you can help me to resolve the issue !
Best regards,
Andres Alarcon

![image](https://user-images.githubusercontent.com/46609931/119185576-79406700-ba3c-11eb-9950-cb585ab1f012.png)
![image](https://user-images.githubusercontent.com/46609931/119185626-8a897380-ba3c-11eb-9f00-7446d9922bc0.png)

**Comment by markmhx** [comment]
The unlocking schedule on Stacks 2.0 is slightly different than the one previously on Stacks 1.0, so it's expected behavior that your STX will unlock a bit later each month than before.

The older stacks wallet here shows a larger value since it still pulls data from the read-only Stacks 1.0 blockchain, but that data is essentially outdated and inaccurate now whereas the Stacks 2.0 blockchain data as seen in the explorer and newer wallet is definitive.

Please wait until the next estimate date as shown in the explorer for your address. Your STX should unlock then.
