### ISSUE TITLE
[4.3.0] Bug: <describe issue>

### ISSUE THREAD

**Issue by doeboy1** [blockstack/stacks-wallet#833]
I sent a certain amount of STX to the Stacks wallet and its taking hours to process. How long does it take to receive funds into the wallet?

Bug found testing Stacks Wallet build undefined, 4.3.0.

**Comment by kyranjamie** [comment]
Sorry to hear this @doeboy1

This could well be due to slow network conditions, I'm not sure without more information. Check the Stacks explorer to follow the transaction.

Reopen this issue if the wallet reflects different information than the explorer, otherwise this isn't a wallet-specific issue.
