### ISSUE TITLE
Show pending inbound transactions via send-many

### ISSUE THREAD

**Issue by manjeet0001** [blockstack/stacks-wallet#933]
Bug found testing Hiro Wallet build undefined, 4.5.3.

**Comment by manjeet0001** [comment]
my fund is not showing me .binance refunded my fund but am not able to see

**Comment by markmhx** [comment]
Can you provide your wallet address either here or via an email to wallet@hiro.so so we can take a look?

**Comment by manjeet0001** [comment]
my wallet id is     SP3JWB1VQSVER8KFQC7X2SX0PGSXW5NSFJX6DCVX7

**Comment by markmhx** [comment]
It appears the transaction is still pending: https://explorer.stacks.co/txid/0xe34f026a0c146fa862e115c16144426702a462716dc6c197d68527e94f5152f3?chain=mainnet

If this were a normal transaction, it would show up in your wallet already as "pending". However, it's being sent as a "send-many" contract call, and I presume it's not showing up as pending because of that delivery mechanism. 

In any case, it should show up in your wallet once confirmed. In the meantime, I'll modify this issue to expand support for these sorts of pending transactions.

**Comment by manjeet0001** [comment]
Hlo sir since 2 days my transaction was showing pending but now it gone cancelled .how could i get my fund back.   0xe34f026a0c146fa862e115c16144426702a462716dc6c197d68527e94f5152f3    this is my transaction id i have shown you before now it gone cancelled what to do now
